name: base
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - torch
  - transformers
  - beautifulsoup4
  - selenium
  - nltk
  - qiskit
  - openai
  - datasets
  - pip:
    - chromedriver-binary
    
